baseURL = "https://forcebyte.github.io"
languageCode = "en-us"
title = "'That' badly designed HomeLab"
theme = "cactus"
copyright = "You" # cactus will use title if copyright is not set
googleAnalytics = "UA-187534005-1"


# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]
  colortheme = "dark" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default

  # Home page settings
  description = "This is a WIP blog I attempt to maintain in my free time with some various helpful information about my HomeLab, studies, and various learnings in my position as a Site Reliability Engineer."
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = true # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = false # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/forcebyte" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = false # default

  [params.comments]
    enabled = true # default
    engine  = "disqus" # more supported engines will be added.

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/forcebyte"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/patrick-turney-049a79158"
  [[params.social]]
    name = "email"
    link = "example@example.com"  # no need for "mailto:" in the head
