baseURL = "http://example.org/"
languageCode = "en-us"
theme = "cactus"
title = "The 'Lab"

name = "Cactus"
license = "MIT"
licenselink = "https://github.com/monkeyWzr/hugo-theme-cactus/blob/master/LICENSE"
description = "A clean, responsive hugo theme for personal blog. Forked from hexo theme cactus created by @probberechts."
homepage = "https://github.com/monkeyWzr/hugo-theme-cactus"
tags = ["blog", "responsive", "clean"]
features = ["mathjax", "customizable", "color"]
min_version = "0.55"

colortheme = "white"